### ISSUE TITLE
Define kinds of conditional definitions that analyzers / type checkers should support

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#24]
For things like Python 2/3 compatibility we'd often want use conditional type alias definitions. Example:

```python
if PY2:
    text = unicode
else:
    text = str

def f() -> text: ...
```

A static analyzer or a type checker can't support arbitrary conditional definitions. Maybe the PEP should define a minimal set of conditional definitions that should be supported. Here are some ideas:

 - Have some way of checking whether we are on Python 2 or 3. Maybe provide `typing.PY2` and `typing.PY3` constants?
 - Literal `True` / `False` and 1 / 0 should be supported.
 - Maybe platform-specific definitions?
 - Maybe arbitrary boolean constants?

**Comment by ambv** [comment]
I'm ambivalent in terms of supporting `if` statements in the type checker. On one hand this looks like it's useful, on the other it creates issues:

1. unit test coverage will be different depending on the platform used
2. type information might be invalid for a certain combination of `if` statements but valid in others

@gvanrossum?

**Comment by gvanrossum** [comment]
I like Jukka's proposal (the PY2/PY3 distinction was one I asked for myself during an early test drive).

I think there should be a small number of boolean constants for coarse platform and version categories. These are predefined in the type checker, exported by typing.py, and at runtime computed based on the actual platform/version. I propose the following:

- `PY2`
- `PY3` (same as "not PY2")
- `WINDOWS`
- `UNIXOID` (same as "not WINDOWS"; includes Mac)

Note that with suitable stub sets, it should be easy to run the type checker with different settings for these (effectively there are only 4 combinations). (The redundancy is because it often looks awkward to see `if not PY3` or `if not WINDOWS`.)

Furthermore I propose that constant definitions of the form
```
DEBUG = True
```
should be recognized by the type checker (similar to the way it recognizes type aliases) and honored, so that e.g. the following type checks using the actual value for DEBUG.
```
DEBUG = False
...
if DEBUG:
    class Debugger:
        <lots of stuff>
else:
    class Debugger:
        <dummy definitions>
```
If you want to type check with both DEBUG on and DEBUG off you'll have to modify the program between runs of the type checker. This is still useful IMO.

PS. What to do with the predefined `__debug__`? I propose to always assume it is on. (Which is close to the truth -- very few people ever use `python -O`.)

**Comment by ambv** [comment]
"UNIXOID" stands out as a peculiar name.

Fixed in e2e6fc4

**Comment by gvanrossum** [comment]
I am hoping someone will propose a better name instead of UNIXOID. I don't want to call it UNIX because of the trademark (assuming it still exists).

**Comment by vlasovskikh** [comment]
We could use `POSIX` (`os.name` is now `'posix'` at least for for Linux and Mac OS X).

**Comment by gvanrossum** [comment]
Oh. Yes. Good enough, as long as we define POSIX and WINDOWS as mutually exclusive. (There used to be a POSIX mode in Windows NT, not sure if that's still supported, but it would be like proving that 1==0.)
